#include QMK_KEYBOARD_H

#include "rgb_matrix_map.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_NONE
#define RGB_MATRIX_KEYPRESSES
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif

static void set_rgb_indicators(void);

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_INS, KC_MUTE, KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_BSPC, KC_DEL, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_PGUP, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_NUHS, KC_ENT, KC_PGDN, KC_LSFT, KC_NUBS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP, KC_END, KC_LCTL, KC_LGUI, KC_LALT, KC_SPC, KC_RALT, MO(1), KC_RCTL, KC_LEFT, KC_DOWN, KC_RGHT),
    [1] = LAYOUT(KC_TRNS, KC_MYCM, KC_WHOM, KC_CALC, KC_MSEL, KC_MPRV, KC_MNXT, KC_MPLY, KC_MSTP, KC_MUTE, KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_TOG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RESET, KC_TRNS, KC_TRNS, KC_TRNS, RGB_VAI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_HUD, RGB_HUI, KC_TRNS, KC_TRNS, KC_TRNS, NK_TOGG, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_MOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_SPD, RGB_RMOD, RGB_SPI)};

#ifdef ENCODER_ENABLE
bool encoder_update_user(uint8_t index, bool clockwise)
{
    if (clockwise)
    {
        tap_code(KC_VOLU);
    }
    else
    {
        tap_code(KC_VOLD);
    }
    return true;
}
#endif

#ifdef RGB_MATRIX_ENABLE

static uint16_t caps_timer;

// process key pressed
bool process_record_user(uint16_t keycode, keyrecord_t *record)
{
    switch (keycode)
    {
    // caps lock pressed
    case KC_CAPS:
        if (record->event.pressed)
        {
            caps_timer = timer_read();
        }
    }
    // never handle the actual keypress
    return true;
}

// set the rgb indicators
void set_rgb_indicators()
{
    if (host_keyboard_led_state().caps_lock)
    {
        RGB rgb = {128, 128, 128};
        if ((timer_elapsed(caps_timer) / 500) % 2 == 0)
        {
            rgb = hsv_to_rgb(rgb_matrix_config.hsv);
        }
        for (uint8_t i = 0; i < 8; i++)
        {
            rgb_matrix_set_color(LED_SIDE_LEFT[i], rgb.r, rgb.g, rgb.b);
            rgb_matrix_set_color(LED_SIDE_RIGHT[i], rgb.r, rgb.g, rgb.b);
        }
    }
}

void rgb_matrix_indicators_user()
{
    if (rgb_matrix_get_flags() == LED_FLAG_NONE)
    {
        rgb_matrix_set_color_all(0x0, 0x0, 0x0);
    }

    set_rgb_indicators();
}
#endif // RGB_MATRIX_ENABLE
